# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: java
jdk: oraclejdk7

before_install:
  - pip install --user codecov

script:
  - ./gradlew build jacocoTestReport -PdisablePreDex

after_success:
- codecov

notifications:
  email:
    recipients:
      - skrzynecki.krzysztof@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle