language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-24.0.3

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - skrzynecki.krzysztof@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle